---
title: "Forest Growth - ODE and Sobel Sensitivity"
author: "Anna Abelman, Margaret Brickner, & Hannah Garcia"
date: "5/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load packages 
library(tidyverse)
library(purrr)
library(deSolve)
library(sensitivity)
```

```{r}
# read in function
source("forest_growth.R")
```

### ODE
```{r}
# Run the model for 300 years (using the ODE solver)  starting with an initial forest size of 10 kg/C, and using the following parameters: canopy closure threshold of 50 kgC , K = 250 kg C (carrying capacity) , r=  0.01 (exponential growth rate before before canopy closure), g = 2 kg/year (linear growth rate after canopy closure)

# Set all of the parameters so they're easier to update and easier to track. 

forest_parms = list(K=250, r = 0.01, g = 2, Ct = 50)

# Set the years and initial size

years = seq(from=1, to=300, by=1)
initial_size = 10

# Use ODE solver to run the model for 300 years

forest_result = ode(y = initial_size, times = years, func = forest_growth, parms = forest_parms)

# Check out the results

colnames(forest_result)=c("year","size")
head(forest_result)

# Graph the Results. I think that this looks right now. Before it was jumping to 250 at year 162/163. I messed around with a few things (not totally sure what I changed that worked, but it seems to be working now). 

ggplot(as.data.frame(forest_result), aes(year, size))+
  geom_point(colour = "forestgreen", size = .3) + 
  labs(title = "Modeled Forest Growth", x = "Year", y = "Forest Size (kg/C)")+ 
  theme_minimal() +
  theme(axis.line = element_line(color = "dimgrey"), 
        panel.border = element_rect(fill = NA, color = NA), 
        panel.grid.minor.y = element_blank(), 
        panel.grid.minor.x = element_blank()) + 
  scale_x_continuous(expand = c(0.0,1)) + 
  scale_y_continuous(expand = c(0.0,1))

```


### Sobel Sensitivity
```{r}
# Run a sobol sensitivity analysis that explores how the estimated maximum and mean forest size (e.g maximum and mean values of C over the 300 years) varies with the pre canopy closure growth rate (r) and post-canopy closure growth rate (g) and canopy closure threshold and carrying capacity(K)

# Assume that they are all normally distributed with means as given above and standard deviation of 10% of mean value

Pinitial=10
forest_parms = list(K=250, r = 0.01, g = 2, Ct = 50)

# set the number of parameters
np=100
K = rnorm(mean=250, sd=0.1, n=np)
r = rnorm(mean=0.01, sd=0.1, n=np)
g = rnorm(mean=2, sd=0.1, n=np)
X1 = cbind.data.frame(r=r, K=K, g=g)

# repeat to get our second set of samples
K = rnorm(mean=250, sd=0.1, n=np)
r = rnorm(mean=0.01, sd=0.1, n=np)
g = rnorm(mean=2, sd=0.1, n=np)
X2 = cbind.data.frame(r=r, K=K, g=g)

sens_P = soboljansen(model = NULL,X1, X2, nboot = 300)
head(sens_P$X)

# gets results for 300 years (evaluating every year)
simtimes = seq(from=1, to=300, by=1)
parms = list(r=sens_P$X$r[1], K=sens_P$X$K[1], g=sens_P$X$g[1])
result = ode(y=Pinitial, times=simtimes, func=forest_growth, parms=forest_parms)

head(result)
colnames(result)=c("time","P")

result = as.data.frame(result)
ggplot(result, aes(time, P))+geom_point() # basically this yields what maggie did above. Idk what to do after this. I get super confused by her syntax. 


# Graph the results of the sensitivity analysis as a box plot of maximum forest size and a plot of the two sobol indices (S and T)


```



